<?php ob_start() ?>

<section>
    <h1><?= $titleH2 ?> Card / Restricted List</h1>
    
    <form enctype="multipart/form-data" action="models/admin/actionAddUpdateCardsRestrictedList.php" method="POST">
        <fieldset>
            <legend><span><?= $titleH2 ?> Card</span></legend>

            <div>
                <div>
                    <label for="name">Name</label>
                </div>
                <input type="text" id="name" name="name" value="<?= $card["name"] ?>">
                <p id="msgErrorName"></p> 
            </div>
            

            <div>
                <select name="categorie" id="categorie">
                    <option value="0">categorie</option>
                    <?php foreach($listCategory as $categorie): ?>
                    <option value="<?= $categorie["id"] ?>" <?php if(isset($card["id_category"])&&$card["id_category"]==$categorie["id"]): ?>selected <?php endif; ?>><?= $categorie["label"] ?></option>
                    <?php endforeach; ?>
                </select>
                <p id="msgErrorCategorie"></p> 
            </div>



            <div id="conteneurInputFile">
                <div>
                    <label for="file">Select a image <i class="fas fa-download"></i></label>
                </div>
                <?php if($titleH2 == "Add"): ?>
                    <input class="inputFile" type="file" id="file" name="file">     
                <?php endif; ?>
            </div>


            <input type="hidden" id="id" name="id" value="<?= $card["id"] ?>">

            <div>
                <button type="submit">VALIDATE</button>
                <button id="reset" type="reset">CANCEL</button>
            </div>
        </fieldset>
    </form>
</section>
    

<?php 
$content = ob_get_clean()
?>