<?php ob_start() ?>

    <section>
        <h1>COMMENTS MANAGEMENT</h1>
        
        <table>
            <caption>Comments List</caption>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>DATE</th>
                    <th>CONTENT</th>
                    <th>USERS</th>
                    <th>ARTICLE</th>
                    <th colspan="3">ACTIONS</th>  
                </tr>
            </thead>
            <tbody>
                <?php foreach($commentsList as $comment): ?>
                    <tr>
                        <td><?= $comment["id"] ?></td>
                        <td><?= $comment["post_date"] ?></td>
                        <td><?= $comment["reply"] ?></td>
                        <td><?= $comment["user_name"] ?></td>
                        <td><?= $comment["articles_id"] ?> / <?= $comment["title"] ?></td>
                        <td>
                            <?php if($comment["state"]==0){ ?>
                                <a id="show" href="models/admin/actionShowHideComments.php?id=<?= $comment["id"] ?>">SHOW <i class='fas fa-eye'></i></a>    
                            <?php }else{ ?>
                                <a id="hide" href="models/admin/actionShowHideComments.php?id=<?= $comment["id"] ?>">HIDE <i class='fas fa-eye-slash'></i></a>
                            <?php } ?>
                            
                            <a href="updateComments&id=<?= $comment["id"] ?>">UPDATE <i class="fas fa-pen-nib"></i></a>
                            <a id="btnDelete" href="models/admin/actionDeleteComments.php?id=<?= $comment["id"] ?>">DELETE <i class="fas fa-trash-alt"></i></a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        
    </section>

<?php 
$content = ob_get_clean()
?>