<?php ob_start() ?>

    
    <section>
        <h1>RESTRICTED LIST MANAGEMENT</h1>
        <div>
            <a href="addCardsRestrictedList"><i class="far fa-plus-square"></i> Add new Card</a>
        </div>
        
        <table>
            <caption>Restrited cards List</caption>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>NAME</th>
                    <th>VIEW</th>
                    <th>SRC</th>
                    <th>CATEGORIE</th>
                    <th colspan="3">ACTIONS</th>  
                </tr>
            </thead>
            <tbody>
                <?php foreach($listRestrictedList as $card): ?>
                    <tr>
                        <td data-label="ID: "><?= $card["id"] ?></td>
                        <td data-label="NAME: "><?= $card["name"] ?></td>
                        <td><img src="uploadFile/restrictedList/<?= $card["src"] ?>" alt="<?= $card["name"] ?>"></td>
                        <td data-label="SRC: "><?php if(strlen($card["src"])>8){echo(substr($card["src"], 0, 8)."...");} ?></td>
                        <td data-label="CATEGORIE: "><?= $card["label"] ?></td>
                        <td>
                            <?php if($card["state"]==0){ ?>
                                <a id="show" href="models/admin/actionShowHideRestrictedCards.php?id=<?= $card["id"] ?>">SHOW <i class='fas fa-eye'></i></a>    
                            <?php }else{ ?>
                                <a id="hide" href="models/admin/actionShowHideRestrictedCards.php?id=<?= $card["id"] ?>">HIDE <i class='fas fa-eye-slash'></i></a>
                            <?php } ?>
                            <a href="addCardsRestrictedList&id=<?= $card["id"] ?>">UPDATE <i class="fas fa-pen-nib"></i></a>
                            <a id="btnDelete" href="models/admin/actionDeleteCardRestrictedList.php?id=<?= $card["id"] ?>&src=<?= $card["src"] ?>">DELETE <i class="fas fa-trash-alt"></i></a> 
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        
    </section>

<?php 
$content = ob_get_clean()
?>