<?php ob_start() ?>

    <section>
        <h1>CATEGORY MANAGEMENT</h1>
        <div>
            <a href="addCategory"><i class="far fa-plus-square"></i> Add new Categorie</a>
        </div>
        
        <table>
            <caption>Category List</caption>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>NAME</th>
                    <th>P.F</th>
                    <th colspan="3">ACTIONS</th>  
                </tr>
            </thead>
            <tbody>
                <?php foreach($listCategory as $categorie): ?>
                    <tr>
                        <td data-label="ID: "><?= $categorie["id"] ?></td>
                        <td data-label="NAME: "><?= $categorie["label"] ?></td>
                <td data-label="P.F: "><?php if($categorie["play_format"]==1): ?> <i class="fas fa-check"></i><?php else: ?> <i class="fas fa-minus-circle"></i><?php endif; ?></td>
                        <td>
                            <?php if($categorie["state"]==0){ ?>
                                <a id="show" href="models/admin/actionShowHideCategory.php?id=<?= $categorie["id"] ?>">SHOW <i class='fas fa-eye'></i></a>    
                            <?php }else{ ?>
                                <a id="hide" href="models/admin/actionShowHideCategory.php?id=<?= $categorie["id"] ?>">HIDE <i class='fas fa-eye-slash'></i></a>
                            <?php } ?>
                            
                            <a href="addCategory&id=<?= $categorie["id"] ?>">UPDATE <i class="fas fa-pen-nib"></i></a>
                            <a id="btnDelete" href="models/admin/actionDeleteCategory.php?id=<?= $categorie["id"] ?>">DELETE <i class="fas fa-trash-alt"></i></a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        
    </section>

<?php 
$content = ob_get_clean()
?>