<?php ob_start() ?>

    <section>
        <h1>USERS MANAGEMENT</h1>
        
        <table>
            <caption>Users List</caption>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>USER NAME</th>
                    <th>MAIL</th>
                    <th colspan="3">ACTIONS</th>  
                </tr>
            </thead>
            <tbody>
                <?php foreach($listUsers as $user): ?>
                        <tr>
                            <td data-label="ID: "><?= $user["id"] ?></td>
                            <td data-label="USER NAME: "><?= $user["user_name"] ?></td>
                            <td data-label="MAIL: "><?= $user["email"] ?></td>
                            <td>
                                <?php if($user["id"]!=17): ?>
                                <?php if($user["author"]==1){ ?>
                                    <a id="show" href="models/admin/actionUsersAuthor.php?id=<?= $user["id"] ?>">AUTHOR <i class="fas fa-pen-nib"></i></a>    
                                <?php }else{ ?>
                                    <a id="hide" href="models/admin/actionUsersAuthor.php?id=<?= $user["id"] ?>">AUTHOR <i class="fas fa-ban"></i></a>
                                <?php } ?>

                                <?php if($user["admin"]==1){ ?>
                                    <a id="show" href="models/admin/actionUsersAdmin.php?id=<?= $user["id"] ?>">ADMIN <i class="fas fa-user-cog"></i></a>    
                                <?php }else{ ?>
                                    <a id="hide" href="models/admin/actionUsersAdmin.php?id=<?= $user["id"] ?>">ADMIN <i class="fas fa-ban"></i></a>
                                <?php } ?>
                                
                                <a id="btnDelete" href="models/admin/actionDeleteUser.php?id=<?= $user["id"] ?>">DELETE <i class="fas fa-trash-alt"></i></a>
                                <?php endif; ?>
                            </td>
                        </tr>
                    <?php endforeach; ?> 
            </tbody>
        </table>
        
    </section>

<?php 
$content = ob_get_clean()
?>