<?php ob_start() ?>

<section id="dashboardHome">
    <h1>partie admin</h1>
    <div>
       <section class="animate">
           <h2>Articles : <?= $nbrArticles ?> <i class="fas fa-edit"></i></h2>
       </section>

       <section class="animate">
           <h2>Users : <?= $nbrUsers ?> <i class="fas fa-users"></i></h2>
       </section>

       <section class="animate">
           <h2>Comments : <?= $nbrComments ?> <i class="fas fa-comments"></i></h2>
       </section>

       <section class="animate">
           <h2>Category : <?= $nbrCategory ?> <i class="fas fa-folder-open"></i></h2>
       </section>
    </div>
</section>
    

<?php 
$content = ob_get_clean()
?>