<?php ob_start() ?>

    <section>
        <h1>ARTICLES MANAGEMENT</h1>
        <div>
            <a href="addArticles"><i class="far fa-plus-square"></i> Add new Article</a>
        </div>
        
        <table>
            <caption>Articles List</caption>
            <thead>
                <tr>
                    <th>ID</th>
                    <th>IMG</th>
                    <th>TITLE</th>
                    <th>CATEGORIE</th>
                    <th>CONTENT</th>
                    <th>AUTHOR</th>
                    <th>CREATION DATE</th>
                    <th colspan="3">ACTIONS</th>  
                </tr>
            </thead>
            <tbody>
                <?php foreach($listArticles as $article): ?>
                    <tr>
                        <td><?= $article["id"] ?></td>
                        <td><img src="uploadFile/articles/<?= $article["src_img"] ?>" alt="<?= $article["name_img"] ?>" title="name: <?= $article['name_img'] ?> src: <?= $article['src_img'] ?>"></td>
                        <td title="<?= $article["title"] ?>"><?= substr($article["title"],0,10) ?>...</td>
                        <td><?= $article["label"] ?></td>
                        <td><?= substr($article["content"],0,10) ?>...</td>
                        <td><?= $article["user_name"] ?></td>
                        <td><?= $article["creation_date"] ?></td>
                        <td>
                            <?php if($article["state"]==0){ ?>
                                <a id="show" href="models/admin/actionShowHideArticles.php?id=<?= $article["id"] ?>">SHOW <i class='fas fa-eye'></i></a>    
                            <?php }else{ ?>
                                <a id="hide" href="models/admin/actionShowHideArticles.php?id=<?= $article["id"] ?>">HIDE <i class='fas fa-eye-slash'></i></a>
                            <?php } ?>
                            
                            <a href="addArticles&id=<?= $article["id"] ?>">UPDATE <i class="fas fa-pen-nib"></i></a>
                            <a id="btnDelete" href="models/admin/actionDeleteArticles.php?id=<?= $article["id"] ?>&src=<?= $article["src_img"] ?>">DELETE <i class="fas fa-trash-alt"></i></a>
                        </td>
                    </tr>
                <?php endforeach; ?>
            </tbody>
        </table>
        
    </section>

<?php 
$content = ob_get_clean()
?>